name: Benchmarks

on: workflow_dispatch

jobs:
  benchmark:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: 16
        distribution: 'zulu'
    - name: Run benchmarks
      run: mvn -B clean verify -Pbenchmark
